-- public.lekarze definition

-- Drop table

-- DROP TABLE public.lekarze;

CREATE TABLE public.lekarze (
	id_lekarza int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	imie varchar NOT NULL,
	nazwisko varchar NOT NULL,
	specjalizacja varchar NULL,
	CONSTRAINT id_lekarza PRIMARY KEY (id_lekarza)
);


-- public.pacjenci definition

-- Drop table

-- DROP TABLE public.pacjenci;

CREATE TABLE public.pacjenci (
	id_pacjenta int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	imie varchar(50) NOT NULL,
	nazwisko varchar(50) NOT NULL,
	pesel bpchar(11) NULL,
	data_urodzenia date NULL,
	plec bpchar(1) NULL,
	CONSTRAINT pacjenci_pkey PRIMARY KEY (id_pacjenta),
	CONSTRAINT pacjenci_plec_check CHECK ((plec = ANY (ARRAY['M'::bpchar, 'K'::bpchar])))
);


-- public.skierowania definition

-- Drop table

-- DROP TABLE public.skierowania;

CREATE TABLE public.skierowania (
	id_skierowania int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id_pacjenta int4 NULL,
	id_lekarza int4 NULL,
	nazwa_badania varchar(100) NULL,
	data_skierowania date NULL,
	wstepne_rozpoznanie varchar(150) NULL,
	status varchar(15) NULL,
	lokalizacja varchar(50) NULL,
	CONSTRAINT skierowania_pkey PRIMARY KEY (id_skierowania),
	CONSTRAINT skierowania_status_check CHECK (((status)::text = ANY ((ARRAY['wystawione'::character varying, 'zrealizowane'::character varying])::text[]))),
	CONSTRAINT skierowania_id_lekarza_fkey FOREIGN KEY (id_lekarza) REFERENCES public.lekarze(id_lekarza),
	CONSTRAINT skierowania_id_pacjenta_fkey FOREIGN KEY (id_pacjenta) REFERENCES public.pacjenci(id_pacjenta)
);


-- public.badania definition

-- Drop table

-- DROP TABLE public.badania;

CREATE TABLE public.badania (
	id_badania int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id_skierowania int4 NULL,
	data_badania date NULL,
	id_radiologa int4 NULL,
	opis text NULL,
	CONSTRAINT badania_pkey PRIMARY KEY (id_badania),
	CONSTRAINT badania_id_radiologa_fkey FOREIGN KEY (id_radiologa) REFERENCES public.lekarze(id_lekarza),
	CONSTRAINT badania_id_skierowania_fkey FOREIGN KEY (id_skierowania) REFERENCES public.skierowania(id_skierowania)
);


-- public.mri definition

-- Drop table

-- DROP TABLE public.mri;

CREATE TABLE public.mri (
	id_badania int4 NULL,
	pole_magn float8 NULL,
	kontrast bool NULL,
	protokol varchar(50) NULL,
	CONSTRAINT mri_id_badania_fkey FOREIGN KEY (id_badania) REFERENCES public.badania(id_badania)
);


-- public.rtg definition

-- Drop table

-- DROP TABLE public.rtg;

CREATE TABLE public.rtg (
	id_badania int4 NULL,
	dawka_prom float8 NULL,
	projekcja varchar(15) NULL,
	pozycja varchar(50) NULL,
	CONSTRAINT rtg_id_badania_fkey FOREIGN KEY (id_badania) REFERENCES public.badania(id_badania)
);


-- public.tk definition

-- Drop table

-- DROP TABLE public.tk;

CREATE TABLE public.tk (
	id_badania int4 NULL,
	dawka_prom float8 NULL,
	kontrast bool NULL,
	tryb varchar(10) NULL,
	CONSTRAINT tk_tryb_check CHECK (((tryb)::text = ANY ((ARRAY['dect'::character varying, 'sect'::character varying])::text[]))),
	CONSTRAINT tk_id_badania_fkey FOREIGN KEY (id_badania) REFERENCES public.badania(id_badania)
);


-- public.usg definition

-- Drop table

-- DROP TABLE public.usg;

CREATE TABLE public.usg (
	id_badania int4 NULL,
	glowica varchar(20) NULL,
	doppler bool NULL,
	czestotoliwosc float4 NULL,
	CONSTRAINT usg_id_badania_fkey FOREIGN KEY (id_badania) REFERENCES public.badania(id_badania)
);